name: Deploy Lambda with Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'be/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

    - name: Ensure ECR Repository Exists
      run: |
        aws ecr describe-repositories --repository-names meme-generator --region ${{ secrets.AWS_REGION }} || \
        aws ecr create-repository --repository-name meme-generator --region ${{ secrets.AWS_REGION }}

    - name: Authenticate Docker with AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t meme-generator .

    - name: Tag Docker Image
      run: |
        docker tag meme-generator:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/meme-generator:latest

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/meme-generator:latest

    - name: Deploy or Update Lambda Function
      run: |
        FUNCTION_NAME="meme-generator-api"
        IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/meme-generator:latest"

        # Check if the Lambda function already exists
        aws lambda get-function --function-name $FUNCTION_NAME --region ${{ secrets.AWS_REGION }} || FUNCTION_EXISTS=false

        if [ "$FUNCTION_EXISTS" == "false" ]; then
          # Create a new Lambda function
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --package-type Image \
            --code ImageUri=$IMAGE_URI \
            --role ${{ secrets.AWS_LAMBDA_ROLE_ARN }} \
            --region ${{ secrets.AWS_REGION }}
        else
          # Update the existing Lambda function
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --image-uri $IMAGE_URI \
            --region ${{ secrets.AWS_REGION }}
        fi
